JSheen98/coding-bootcamp-project1-movie-recommender

index.html
Added starting files:
* Readme file
* JS file
* CSS file
* Index file
=> Added starting files

index.html
Added Tailwind script to HTML file
=> Added Tailwind

assets/CSS/style.css, index.html
=> added content cards

README.md, assets/CSS/style.css
Added the following:
* Almost fully complete README file
* Added font to CSS file
* Changed Map Modal button color to match hover themes of other buttons
* Cleaned up CSS file
=> Added content to readme file, small CSS changes

assets/CSS/style.css, assets/JS/script.js, index.html
Added functionality to search button and enter button.
=> added events and btn to search bar

assets/CSS/style.css
Added CSS to fix:
* Header
* Sidebar
* Content cards
=> Added missing CSS

assets/CSS/style.css, index.html
=> rowtitlefix

assets/CSS/style.css, index.html
Added a simple footer with Author and project title names. Includes linking to sidebar.
=> Added simple footer

Contact.html, assets/CSS/style.css, index.html
Added page for Contact information
=> Contacthtml

README.md, assets/CSS/style.css, assets/JS/tmdbapi.js, index.html
Added fetch function to pull API info from TMDb and display it dynamically on the first row of cards. Currently, it is pulling for the 'Now Playing' query.
=> Added API functionality for first row

index.html
Noticed that the contact form wasn't linked properly so i just relinked the page.
=> fixed the link to the contact page

assets/JS/script.js, index.html
the script for pulling genres from mdb api
=> genrescript.js

assets/CSS/style.css, assets/JS/script.js, assets/JS/tmdbapi.js, index.html
Clicking a genre in the sidebar makes the second row display the top 5 movies in the selected genre.
Clicking the Top 10 button reruns the function that makes the rows display the top 10 movies rather than reloading the page.
=> Finished Filter

assets/CSS/style.css, index.html
=> Start of responsive design

Contact.html, assets/CSS/style.css, assets/JS/script.js, index.html
Added the following:
* User search brings up a search results row with 5 related movies
* Added more to responsive design
=> Added TMDb search results, and continued responsive design

assets/JS/googapi.js
=> google-api-icons

assets/CSS/style.css, assets/JS/googapi.js, assets/JS/script.js, assets/JS/tmdbapi.js, index.html
This branch includes the following:
* Code clean up
* Added function to make local storage load on refresh
* Fixed search button (wasn't logging user input as <li>'s
=> Cleaned up code, added function to load local storage on reload

assets/CSS/style.css, assets/JS/script.js, index.html
Added the following:
* Fixed error when results wouldn't come back fully
* Added responsive design
=> Added responsive design functionality

assets/CSS/style.css
Fixed padding issue with side menu 'Genre' button spacing.
=> Fixed small spacing issue in side nav

index.html
=> Fixed some side menu links
